# Reusable Fields and Fieldsets

flexible: &FLEXIBLE
  - label: 'Text Block'
    name: 'text_block'
    widget: object
    fields:
    - { label: Text, name: text, widget: markdown }
  - label: 'Image'
    name: 'image'
    widget: object
    hint: 'If page type is a site page, choose it here'
    fields:
    - { label: Full Width, name: full_width, widget: boolean, required: false }
    - { label: Image, name: image, widget: image, required: false }
    - { label: Image Description, name: alt, widget: string }
  - label: 'Image and Text'
    name: 'image_by_text'
    widget: object
    fields:
    - { label: Text, name: text, widget: markdown }
    - label: 'Image'
      name: 'image'
      widget: object
      fields:
      - { label: Image, name: image, widget: image, required: false }
      - { label: Image Description, name: alt, widget: string }
  - label: 'Video'
    name: 'video'
    widget: object
    fields:
    - { label: 'Youtube Embed', name: 'youtube_embed', widget: string }
  - label: 'Band Members'
    name: 'band_members'
    widget: object
    fields:
    - label: 'Member'
      name: 'member'
      widget: relation
      collection: 'Members'
      search_fields: ['name']
      display_fields: ['name']
      value_field: '{{slug}}'
      multiple: true
      hint: 'Select the band members and the order in which to display them'

# Site Config

backend:
  name: git-gateway
  repo: alexrichardsweb/kssouls-nuxt
  branch: main # Branch to update (optional; defaults to master)
  local_backend: true
#publish_mode: editorial_workflow
media_folder: "static/images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "images/uploads"
collections:
  - name: 'Settings'
    label: 'Site Settings'
    folder: 'content/settings'
    format: 'frontmatter'
    slug: 'settings'
    editor:
      preview: false
    fields:
      - { label: 'Site Settings Name', name: 'site_settings_name', widget: 'string', default: 'Site Settings' }
      - { label: 'Site Name', name: 'site_name', widget: 'string' }
      - { label: 'Logo', name: 'logo', widget: 'image', required: false }
      - label: 'Social'
        name: 'social'
        widget: list
        fields:
          - label: 'Social Media'
            name: 'social_media'
            widget: object
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Link', name: 'link', widget: 'string' }
      - label: 'Menu Pages'
        name: 'menu_pages'
        widget: list
        fields:
          - label: 'Menu Item'
            name: 'Menu Item'
            widget: object
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - label: 'Page Type'
                name: 'page_type'
                widget: 'select'
                default: 'internal'
                options:
                  - { label: "Site Page", value: "internal" }
                  - { label: "External Link", value: "external" }
              - { label: 'Link', name: 'link', widget: 'string', hint: 'If page type is an external link, enter it here', required: false }
              - label: 'Page'
                name: 'page'
                widget: 'relation'
                collection: 'Pages'
                search_fields: ['title']
                display_fields: ['title']
                value_field: '{{slug}}'
                hint: 'If page type is a site page, choose it here'
                required: false
  - name: 'Pages'
    label: 'Pages'
    folder: 'content/pages'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - label: 'Content Blocks'
        name: 'sections'
        widget: 'list'
        types: *FLEXIBLE
  - name: 'Videos'
    label: 'Videos'
    folder: 'content/videos'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Video Description', name: 'video_description', widget: 'markdown' }
      - label: "Video Type"
        name: "video_type"
        widget: "select"
        options:
          - { label: "Facebook", value: "facebook" }
          - { label: "Youtube", value: "youtube" }
      - { label: 'Video URL', name: 'video_url', widget: 'string' }

  - name: 'Shows'
    label: 'Shows'
    folder: 'content/shows'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'show_description', widget: 'markdown', required: false }
      - { label: 'Date and Time', name: 'show_date_time', widget: 'datetime', date_format: 'ddd Do MMMM YYYY' }
      - { label: 'Event URL', hint: 'Link to Facebook event/festival website', name: 'show_url', widget: 'string', required: false }

      - label: 'Location'
        name: 'show_location'
        widget: 'object'
        fields:
        - { label: 'Location Name', hint: 'Name of club/town or festival', name: 'location_name', widget: 'string' }
        - { label: 'Location URL', hint: 'If the club/festival has a website of social media page put it here', name: 'location_url', widget: 'string', required: false }

      - label: 'Tickets'
        name: 'show_tickets'
        widget: 'object'
        fields:
        - { label: 'Ticket Price', hint: 'Include currency e.g. £5', name: 'ticket_price', widget: 'string', required: false }
        - { label: 'Ticket URL', hint: 'Add if tickets are available to buy online', name: 'ticket_url', widget: 'string', required: false }
        - { label: 'Ticket Info', hint: 'Further info about tickets e.g. "Available on the door"',  name: 'ticket_info', widget: 'markdown', required: false }

      - { label: 'Promo Video', name: 'show_video', widget: 'string', required: false }
      - { label: 'Promo Image', name: 'show_image', widget: 'image', required: false }

  - name: 'Home'
    label: 'Homepage'
    folder: 'content/home'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

      - label: 'Banner'
        name: 'banner'
        widget: 'object'
        fields:
        - {label: Image, name: image, widget: image}
        - {label: Banner Text, name: banner_text, widget: string}

      - label: 'Content Blocks'
        name: 'sections'
        widget: 'list'
        types: *FLEXIBLE
  - name: 'Members'
    label: 'Members'
    folder: 'content/members'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: Name, name: name, widget: string }
      - { label: Image, name: image, widget: image, required: false }